// Curated starting suggestions; a major never limits what a student may select.
export const MAJOR_OPTIONS = [
  {
    id: 'technology',
    label: 'Computing and technology',
    majors: [
      'Computer Science',
      'Information Technology',
      'Software Engineering',
      'Cybersecurity',
      'Computer Engineering',
      'CS',
      'IT',
    ],
    interests: [
      'Building websites',
      'Solving technical problems',
      'Working with data',
      'Mobile apps',
      'Artificial intelligence',
      'Cybersecurity',
      'Game development',
      'Cloud computing',
      'Robotics',
      'Open-source software',
      'Accessible technology',
      'Automation',
      'Computer networks',
      'Developer tools',
      'Technology for social good',
    ],
    skills: [
      'HTML and CSS',
      'JavaScript',
      'Python',
      'SQL',
      'Git',
      'Java',
      'C++',
      'React',
      'Linux',
      'API development',
      'Debugging',
      'Software testing',
      'Data structures',
      'Technical writing',
      'Teamwork',
    ],
  },
  {
    id: 'data',
    label: 'Mathematics and data',
    majors: ['Data Science', 'Mathematics', 'Statistics', 'Applied Mathematics', 'Analytics'],
    interests: [
      'Working with data',
      'Statistical modeling',
      'Data visualization',
      'Machine learning',
      'Financial modeling',
      'Public policy analysis',
      'Sports analytics',
      'Healthcare analytics',
      'Climate data',
      'Market research',
      'Forecasting',
      'Experiment design',
      'Optimization',
      'Scientific computing',
      'Explaining complex ideas',
    ],
    skills: [
      'Python',
      'SQL',
      'Spreadsheets',
      'R',
      'Statistics',
      'Data visualization',
      'Data cleaning',
      'Probability',
      'Linear algebra',
      'Research methods',
      'Experiment design',
      'Git',
      'Critical thinking',
      'Presentation skills',
      'Technical writing',
    ],
  },
  {
    id: 'business',
    label: 'Business, finance, and economics',
    majors: [
      'Business Administration',
      'Business',
      'Finance',
      'Accounting',
      'Economics',
      'Marketing',
      'Management',
      'Supply Chain Management',
    ],
    interests: [
      'Entrepreneurship',
      'Marketing strategy',
      'Consumer behavior',
      'Finance and investing',
      'Accounting and auditing',
      'Business analytics',
      'Operations management',
      'Supply chain logistics',
      'Human resources',
      'Sales and partnerships',
      'Economic policy',
      'Consulting',
      'Product management',
      'Sustainable business',
      'Working with data',
    ],
    skills: [
      'Spreadsheets',
      'Financial analysis',
      'Budgeting',
      'Market research',
      'Business writing',
      'Presentation skills',
      'Project coordination',
      'SQL',
      'Data visualization',
      'Accounting basics',
      'Negotiation',
      'Customer service',
      'Teamwork',
      'Problem solving',
      'Leadership',
    ],
  },
  {
    id: 'engineering',
    label: 'Engineering',
    majors: [
      'Engineering',
      'Mechanical Engineering',
      'Electrical Engineering',
      'Civil Engineering',
      'Chemical Engineering',
      'Industrial Engineering',
      'Aerospace Engineering',
      'Biomedical Engineering',
    ],
    interests: [
      'Product design',
      'Robotics',
      'Renewable energy',
      'Transportation systems',
      'Infrastructure',
      'Manufacturing',
      'Electronics',
      'Materials science',
      'Aerospace systems',
      'Water systems',
      'Biomedical devices',
      'Automation',
      'Sustainable design',
      'Solving technical problems',
      'Engineering research',
    ],
    skills: [
      'CAD',
      'Technical drawing',
      'Python',
      'MATLAB',
      'Spreadsheets',
      'Engineering calculations',
      'Prototyping',
      'Data analysis',
      'Lab documentation',
      'Technical writing',
      'Safety procedures',
      'Project coordination',
      'Problem solving',
      'Teamwork',
      'Presentation skills',
    ],
  },
  {
    id: 'design',
    label: 'Design and creative work',
    majors: [
      'Design',
      'Graphic Design',
      'Visual Arts',
      'Art',
      'UX Design',
      'Animation',
      'Film',
      'Architecture',
    ],
    interests: [
      'User experience design',
      'Visual storytelling',
      'Brand identity',
      'Digital illustration',
      'Animation',
      'Photography',
      'Film production',
      'Typography',
      'Accessible design',
      'Interactive media',
      'Product design',
      'Game art',
      'Exhibition design',
      'Building websites',
      'Creative direction',
    ],
    skills: [
      'Figma',
      'Adobe Illustrator',
      'Adobe Photoshop',
      'Sketching',
      'Typography',
      'Layout design',
      'Prototyping',
      'User research',
      'Photography',
      'Video editing',
      'HTML and CSS',
      'Presentation skills',
      'Creative writing',
      'Teamwork',
      'Project coordination',
    ],
  },
  {
    id: 'psychology',
    label: 'Psychology and social sciences',
    majors: [
      'Psychology',
      'Sociology',
      'Social Work',
      'Criminology',
      'Anthropology',
      'Political Science',
    ],
    interests: [
      'Human behavior',
      'Mental health research',
      'Community development',
      'Social policy',
      'User research',
      'Child development',
      'Organizational behavior',
      'Public health',
      'Education research',
      'Criminal justice',
      'Cultural studies',
      'Behavioral economics',
      'Survey research',
      'Advocacy',
      'Working with data',
    ],
    skills: [
      'Research methods',
      'Survey design',
      'Interviewing',
      'Statistics',
      'Spreadsheets',
      'R',
      'Data analysis',
      'Academic writing',
      'Active listening',
      'Presentation skills',
      'Qualitative analysis',
      'Literature reviews',
      'Teamwork',
      'Critical thinking',
      'Community outreach',
    ],
  },
  {
    id: 'science',
    label: 'Natural and life sciences',
    majors: [
      'Biology',
      'Chemistry',
      'Physics',
      'Environmental Science',
      'Biochemistry',
      'Neuroscience',
      'Geology',
    ],
    interests: [
      'Laboratory research',
      'Environmental conservation',
      'Biotechnology',
      'Ecology',
      'Genetics',
      'Climate science',
      'Materials research',
      'Science communication',
      'Public health',
      'Astronomy',
      'Marine science',
      'Scientific computing',
      'Field research',
      'Sustainable agriculture',
      'Working with data',
    ],
    skills: [
      'Lab documentation',
      'Research methods',
      'Data analysis',
      'Statistics',
      'Spreadsheets',
      'Python',
      'Scientific writing',
      'Literature reviews',
      'Microscopy',
      'Experimental design',
      'Sample preparation',
      'Safety procedures',
      'Critical thinking',
      'Teamwork',
      'Presentation skills',
    ],
  },
  {
    id: 'health',
    label: 'Health and wellbeing',
    majors: [
      'Nursing',
      'Public Health',
      'Health Sciences',
      'Nutrition',
      'Kinesiology',
      'Exercise Science',
    ],
    interests: [
      'Community health',
      'Health education',
      'Nutrition',
      'Exercise and wellbeing',
      'Health policy',
      'Patient advocacy',
      'Healthcare administration',
      'Health technology',
      'Epidemiology',
      'Health equity',
      'Aging and wellbeing',
      'Maternal and child health',
      'Public health research',
      'Science communication',
      'Working with data',
    ],
    skills: [
      'Health communication',
      'Research methods',
      'Data analysis',
      'Spreadsheets',
      'Statistics',
      'Active listening',
      'Academic writing',
      'Community outreach',
      'Teamwork',
      'Presentation skills',
      'Project coordination',
      'Literature reviews',
      'Critical thinking',
      'Documentation',
      'Health education',
    ],
  },
  {
    id: 'education',
    label: 'Education and learning',
    majors: [
      'Education',
      'Elementary Education',
      'Secondary Education',
      'Special Education',
      'Early Childhood Education',
    ],
    interests: [
      'Teaching and tutoring',
      'Child development',
      'Curriculum design',
      'Educational technology',
      'Inclusive education',
      'Literacy',
      'STEM education',
      'Student support',
      'Learning research',
      'Community programs',
      'Youth mentoring',
      'Language learning',
      'Education policy',
      'Creative learning',
      'Accessible technology',
    ],
    skills: [
      'Lesson planning',
      'Tutoring',
      'Presentation skills',
      'Active listening',
      'Written communication',
      'Research methods',
      'Spreadsheets',
      'Group facilitation',
      'Learning material design',
      'Teamwork',
      'Time management',
      'Problem solving',
      'Project coordination',
      'Community outreach',
      'Digital tools',
    ],
  },
  {
    id: 'humanities',
    label: 'Humanities and communication',
    majors: [
      'English',
      'History',
      'Philosophy',
      'Communications',
      'Communication',
      'Journalism',
      'Languages',
      'International Relations',
    ],
    interests: [
      'Writing and editing',
      'Journalism',
      'Cultural research',
      'Public relations',
      'Digital media',
      'Policy research',
      'Publishing',
      'Language learning',
      'Historical research',
      'Community advocacy',
      'Museum work',
      'Storytelling',
      'Ethics and technology',
      'Event planning',
      'Science communication',
    ],
    skills: [
      'Academic writing',
      'Creative writing',
      'Editing',
      'Research methods',
      'Literature reviews',
      'Presentation skills',
      'Written communication',
      'Interviewing',
      'Fact checking',
      'Social media content',
      'Spreadsheets',
      'Critical thinking',
      'Teamwork',
      'Project coordination',
      'Public speaking',
    ],
  },
  {
    id: 'general',
    label: 'Exploring your options',
    majors: ['Undeclared', 'Undecided', 'General Studies'],
    interests: [
      'Building websites',
      'Solving technical problems',
      'Working with data',
      'Helping people',
      'Creative work',
      'Starting a business',
      'Environmental sustainability',
      'Scientific research',
      'Writing and storytelling',
      'Teaching and mentoring',
      'Community projects',
      'Designing products',
      'Organizing events',
      'Finance and investing',
      'Understanding human behavior',
    ],
    skills: [
      'Written communication',
      'Presentation skills',
      'Teamwork',
      'Problem solving',
      'Time management',
      'Research methods',
      'Spreadsheets',
      'Customer service',
      'Leadership',
      'Project coordination',
      'Digital tools',
      'Active listening',
      'Critical thinking',
      'Creative writing',
      'Data analysis',
    ],
  },
];
