// Starter curriculum data. PostgreSQL owns editable copies after first initialization.
const definitions = [
  [
    'software',
    'Software Engineer',
    'Build and test useful software.',
    {
      Programming: ['Python', 'JavaScript', 'Java', 'C++', 'Data Structures'],
      'Web development': ['HTML/CSS', 'React', 'Node.js', 'APIs', 'SQL'],
      Tools: ['Git', 'GitHub', 'Docker', 'Testing'],
    },
    ['Python', 'JavaScript', 'Git', 'SQL', 'Data Structures', 'APIs', 'React', 'Testing'],
    [
      'Programming Fundamentals',
      'Git & GitHub',
      'Data Structures & Algorithms',
      'Databases',
      'APIs',
      'Build Portfolio Projects',
      'Technical Interview Preparation',
      'Apply for Internships / Entry-Level Positions',
    ],
    ['technology', 'problem-solving'],
    'desk',
  ],
  [
    'cybersecurity',
    'Cybersecurity Analyst',
    'Investigate risks and protect systems.',
    {
      Systems: ['Networking', 'Linux', 'Python'],
      Security: [
        'Risk assessment',
        'Security monitoring',
        'Incident response',
        'Access control',
        'Security documentation',
      ],
    },
    [
      'Networking',
      'Linux',
      'Python',
      'Risk assessment',
      'Security monitoring',
      'Incident response',
      'Access control',
      'Security documentation',
    ],
    [
      'Networking Basics',
      'Linux Practice',
      'Security Fundamentals',
      'Analyze Sample Logs',
      'Practice Incident Response',
      'Build a Safe Lab Case Study',
      'Practice Security Interviews',
      'Apply for Security Opportunities',
    ],
    ['technology', 'problem-solving'],
    'desk',
  ],
  [
    'data-analyst',
    'Data Analyst',
    'Use data to answer practical questions.',
    {
      Analysis: ['Spreadsheets', 'SQL', 'Statistics', 'Data cleaning'],
      Tools: ['Python', 'Data visualization'],
      Communication: ['Presentation skills', 'Research'],
    },
    [
      'Spreadsheets',
      'SQL',
      'Statistics',
      'Data cleaning',
      'Python',
      'Data visualization',
      'Presentation skills',
      'Research',
    ],
    [
      'Spreadsheet Analysis',
      'SQL Queries',
      'Statistics Fundamentals',
      'Clean a Public Dataset',
      'Build a Dashboard',
      'Publish an Analysis Case Study',
      'Practice Analysis Interviews',
      'Apply for Analyst Opportunities',
    ],
    ['numbers', 'problem-solving'],
    'desk',
  ],
  [
    'finance',
    'Financial Analyst',
    'Research financial information and support decisions.',
    {
      Finance: ['Financial statements', 'Financial modeling', 'Budgeting', 'Accounting basics'],
      Analysis: ['Spreadsheets', 'Statistics', 'Research', 'Presentation skills'],
    },
    [
      'Financial statements',
      'Financial modeling',
      'Budgeting',
      'Accounting basics',
      'Spreadsheets',
      'Statistics',
      'Research',
      'Presentation skills',
    ],
    [
      'Read Financial Statements',
      'Spreadsheet Modeling',
      'Budgeting Fundamentals',
      'Compare Public Company Reports',
      'Build a Sample Financial Model',
      'Write an Investment Case Study',
      'Practice Finance Interviews',
      'Apply for Finance Opportunities',
    ],
    ['numbers', 'leadership'],
    'desk',
  ],
  [
    'accounting',
    'Accountant',
    'Organize records and explain financial activity.',
    {
      Accounting: ['Bookkeeping', 'Financial statements', 'Reconciliation', 'Accounting basics'],
      Practice: ['Spreadsheets', 'Attention to detail', 'Ethics', 'Communication'],
    },
    [
      'Bookkeeping',
      'Financial statements',
      'Reconciliation',
      'Accounting basics',
      'Spreadsheets',
      'Attention to detail',
      'Ethics',
      'Communication',
    ],
    [
      'Accounting Fundamentals',
      'Bookkeeping Practice',
      'Spreadsheet Reconciliation',
      'Prepare Sample Financial Statements',
      'Research Local Credential Requirements',
      'Build an Accounting Case Study',
      'Practice Accounting Interviews',
      'Apply for Accounting Opportunities',
    ],
    ['numbers', 'problem-solving'],
    'desk',
  ],
  [
    'police',
    'Police Officer',
    'Serve communities and respond to public safety needs.',
    {
      Community: ['Communication', 'Conflict resolution', 'Teamwork', 'Ethics'],
      Practice: ['Report writing', 'Critical thinking', 'Physical fitness', 'Observation'],
    },
    [
      'Communication',
      'Conflict resolution',
      'Teamwork',
      'Ethics',
      'Report writing',
      'Critical thinking',
      'Physical fitness',
      'Observation',
    ],
    [
      'Research Local Agency Eligibility',
      'Learn Community Policing Principles',
      'Practice Clear Report Writing',
      'Build a Sustainable Fitness Plan',
      'Practice Conflict Resolution',
      'Find Community Service Experience',
      'Review Agency Selection Processes',
      'Apply to Eligible Agency Programs',
    ],
    ['people', 'leadership'],
    'field',
  ],
  [
    'law',
    'Attorney',
    'Research legal issues and advocate for clients.',
    {
      Analysis: ['Legal research', 'Critical thinking', 'Research', 'Attention to detail'],
      Advocacy: ['Writing', 'Communication', 'Ethics', 'Negotiation'],
    },
    [
      'Legal research',
      'Critical thinking',
      'Research',
      'Attention to detail',
      'Writing',
      'Communication',
      'Ethics',
      'Negotiation',
    ],
    [
      'Research Education and Local Licensing Routes',
      'Practice Legal Research',
      'Read and Summarize a Public Case',
      'Build an Argument Outline',
      'Explore Legal Volunteering',
      'Plan Education or Admissions Next Steps',
      'Practice Professional Conversations',
      'Apply for Appropriate Legal Experience',
    ],
    ['people', 'problem-solving'],
    'mixed',
  ],
  [
    'ux',
    'UX Designer',
    'Research user needs and design understandable experiences.',
    {
      Research: ['User research', 'Usability testing', 'Communication'],
      Design: ['Figma', 'Wireframing', 'Prototyping', 'Accessibility', 'Visual design'],
    },
    [
      'User research',
      'Usability testing',
      'Communication',
      'Figma',
      'Wireframing',
      'Prototyping',
      'Accessibility',
      'Visual design',
    ],
    [
      'Learn User-Centered Design',
      'Practice Figma and Wireframes',
      'Plan a Small Research Study',
      'Build an Accessible Prototype',
      'Run a Usability Test',
      'Publish a Portfolio Case Study',
      'Practice Design Interviews',
      'Apply for Design Opportunities',
    ],
    ['creativity', 'people'],
    'mixed',
  ],
];
export const CAREERS = definitions.map(
  ([id, name, description, categories, skills, titles, affinities, environment]) => ({
    id,
    name,
    description,
    categories,
    skills,
    affinities,
    environment,
    stretch:
      'This starter plan is guidance. Check actual postings and local education, licensing, and eligibility requirements.',
    source: {
      title: 'Career exploration',
      url: 'https://www.mynextmove.org/find/search?s=' + encodeURIComponent(name),
    },
    milestones: titles.map((title, index) => ({
      id:
        index === 7
          ? 'apply'
          : `milestone-${['one', 'two', 'three', 'four', 'five', 'six', 'seven'][index]}`,
      title,
      category: index === 7 ? 'Applications' : index === 5 ? 'Project' : 'Skills',
      hours: 1,
      why: 'Start with one focused practice session, then use feedback to decide what to do next. Completing a session does not certify mastery.',
      deliverable: `Document a concrete result from ${title.toLowerCase()}, what you learned, and what still needs practice.`,
      dependencies: [],
      resource: {
        title: 'Explore this career',
        url: 'https://www.mynextmove.org/find/search?s=' + encodeURIComponent(name),
      },
    })),
  }),
);
export const SITUATIONS = [
  'High School Student',
  'College Student',
  'Recent Graduate',
  'Working Professional',
  'Changing Careers',
  'Just Exploring',
];
export const DEGREES = ['Associate', 'Bachelor’s', 'Master’s', 'Doctorate', 'Certificate', 'Other'];
export const EXPERIENCES = [
  'Personal Projects',
  'School Projects',
  'Internship',
  'Part-Time Job',
  'Full-Time Job',
  'Volunteer Experience',
  'Certifications',
  'None Yet',
];
export const LEVELS = ['Beginner', 'Intermediate', 'Advanced'];
export const PREFERENCES = [
  'people',
  'technology',
  'numbers',
  'creativity',
  'problem-solving',
  'leadership',
];
export const defaultCareers = async () => structuredClone(CAREERS);
export const careerMap = (careers) =>
  Object.fromEntries(careers.map((career) => [career.id, career]));
